### ISSUE TITLE
Is the framework fast?

### ISSUE THREAD

**Issue by BunyaminEfe** [atabasch/atabasch-framework#1]
I will be glad if you give me feedback

**Comment by atabasch** [comment]
If you use **Nginx** webserver and **PHP version 8**, it's much faster than other common frameworks.

**Comment by BunyaminEfe** [comment]
thank you for your feedback

**Comment by atabasch** [comment]
You're welcome. It was my pleasure to help.

**Comment by BunyaminEfe** [comment]
thanks gg
